// جميع النصوص باللغتين
window.siteLangData = {
  ar: {
    nav_home: 'الرئيسية',
    nav_about: 'من أنا',
    nav_gallery: 'الأعمال',
    nav_contact: 'تواصل',
    hero_title: 'مرحباً بكم في معرض المصور',
    hero_desc: 'مجموعة من أفضل أعمالي في التصوير الفوتوغرافي',
    about_title: 'من أنا',
    about_desc: 'أنا مصور محترف أقدم أعمالاً فنية متنوعة في مجال التصوير الفوتوغرافي.',
    gallery_title: 'معرض الأعمال',
    gallery_desc: 'مجموعة من أفضل أعمالي في التصوير الفوتوغرافي',
    contact_title: 'تواصل معي',
    contact_name: 'الاسم',
    contact_email: 'البريد الإلكتروني',
    contact_message: 'رسالتك',
    contact_btn: 'إرسال',
    contact_follow: 'تابعني على:',
    footer: '© 2025 معرض المصور',
  lang_btn: 'English',
  dark_btn: '🌙 داكن',
  light_btn: '☀️ فاتح',
  brand: 'أحمد للتصوير',
  cta: 'شاهد أعمالي',
  },
  en: {
    nav_home: 'Home',
    nav_about: 'About',
    nav_gallery: 'Gallery',
    nav_contact: 'Contact',
    hero_title: 'Welcome to the Photographer Portfolio',
    hero_desc: 'A collection of my best photography works',
    about_title: 'About Me',
    about_desc: 'I am a professional photographer offering a variety of artistic photography works.',
    gallery_title: 'Gallery',
    gallery_desc: 'A collection of my best photography works',
    contact_title: 'Contact Me',
    contact_name: 'Name',
    contact_email: 'Email',
    contact_message: 'Your Message',
    contact_btn: 'Send',
    contact_follow: 'Follow me on:',
    footer: '© 2025 Photographer Portfolio',
  lang_btn: 'العربية',
  dark_btn: '🌙 Dark',
  light_btn: '☀️ Light',
  brand: 'Ahmed Photography',
  cta: 'My Projects',
  }
};
